create table clashcards ( `id` int(11),
  `nombre` varchar(50),
  `calidad` varchar(50),
  `tipo` varchar(50),
  `arena` int(11),
  `elixir` int(11),
  `velocidad` varchar(50),
  `desplazamiento` varchar(50));
INSERT INTO `clashcards` (`id`, `nombre`, `calidad`, `tipo`, `arena`, `elixir`,`velocidad`,`desplazamiento`) VALUES (1,'Mini P.E.K.K.A', 'Especial', 'Tropa',0,4,'Alta','Tierra'),
(2,'Arqueras','Comun','Tropa',0,3,'Media','Tierra'),
(3,'Bombardero','Comun','Tropa',0,3,'Media','Tierra'),
(4,'Mosquetera','Especial','Tropa',0,4,'Media','Tierra'),
(5,'Gigante','Especial','Tropa',0,5,'Baja','Tierra'),
(6,'Caballero','Comun','Tropa',0,3,'Media','Tierra'),
(7,'Horda de Esqueletos','Epica','Tropa',0,3,'Alta','Tierra'),
(8,'Bruja','Epica','Tropa',0,5,'Media','Tierra'),
(9,'Bebe Dragon','Epica','Tropa',0,4,'Alta','Aire'),
(10,'Principe','Epica','Tropa',0,5,'Media','Tierra'),
(11,'Bola de Fuego','Especial', 'Hechizo',0,4,'N/A','N/A'),
(12,'Flechas','Comun','Hechizo',0,3,'N/A','N/A'),
(13,'Duendes','Comun','Tropa',1,2,'Muy Alta','Tierra'),
(14,'Valkiria','Especial','Tropa',1,4,'Media','Tierra'),
(15,'Duendes con Lanza','Comun','Tropa',1,2,'Muy Alta','Tierra'),
(16,'Choza de duendes','Especial','Estructura',1,5,'Muy Alta','Tierra'),
(17,'Barril de duendes','Epica','Hechizo',1,3,'N/A','Tierra'),
(18,'Rayo','Epica','Hechizo',1,6,'N/A','N/A'),
(19,'Esbirros', 'Comun','Tropa',2,3,'Alta','Aire'),
(20,'Esqueletos','Comun','Tropa',2,1,'Alta','Tierra'),
(21,'Torre bombardera','Especial','Estructura',2,5,'N/A','N/A'),
(22,'Lapida','Especial','Estructura',2,3,'N/A','N/A'),
(23,'Globo bombastico','Epica','Tropa',2,5,'Media','Aire'),
(24,'Esqueleto Gigante','Epica','Tropa',2,5,'Media','Tierra'),
(25,'Barbaros','Comun','Tropa',3,5,'Media','Tierra'),
(26,'Cañon','Comun','Estructura',3,3,'N/A','N/A'),
(27,'Choza de Barbaros','Especial','Estructura',3,7,'Media','Tierra'),
(28,'Cohete','Especial','Hechizo',3,6,'N/A','N/A'),
(29,'Ballesta','Epica','Estructura',3,6,'N/A','N/A'),
(30,'Furia','Epica','Hechizo',3,2,'N/A','N/A'),
(31,'Horda de Esbirrios','Comun','Tropa',4,5,'Alta','Aire'),
(32,'Torre Tesla','Comun','Estructura',4,4,'N/A','N/A'),
(33,'Montapuercos','Especial','Tropa',4,4,'Muy Alta','Tierra'),
(34,'Torre Infernal','Especial','Estructura',4,5,'N/A','N/A'),
(35,'P.E.K.K.A','Epica','Tropa',4,7,'Baja','Tierra'),
(36,'Hielo','Epica','Hechizo',4,4,'N/A','N/A'),
(37,'Dragon infernal','Legendaria','Tropa',4,4,'Media','Aire'),
(38,'Sabueso de lava','Legendaria','Tropa',4,7,'Baja','Aire'),
(39,'Descarga','Comun','Hechizo',5,2,'N/A','N/A'),
(40,'Espiritus de fuego','Comun','Tropa',5,2,'Muy Alta','Tierra'),
(41,'Horno','Especial','Estructura',5,5,'N/A','N/A'),
(42,'Mago','Especial','Tropa',5,5,'Media','Tierra'),
(43,'Espejo','Epica','Hechizo',5,2 AND 3 AND 4 AND 5 AND 6 AND 7 AND 8 AND 9 AND 10, 'N/A','N/A'),
(44,'Veneno','Epica','Hechizo',5,4,'N/A','N/A'),
(45,'Mago de Hielo','Legendaria','Tropa',5,3,'Media','Tierra'),
(46,'Cementerio','Legendaria','Hechizo',5,5,'N/A','N/A'),
(47,'Mortero','Comun','Estructura',6,4,'N/A','N/A'),
(48,'Recolector de elixir','Especial','Estructura',6,6,'N/A','N/A'),
(49,'Ariete de batalla','Especial','Tropa',6,4,'Media','Tierra'),
(50,'Tornado','Epica','Hechizo',6,3,'N/A','N/A'),
(51,'Golem','Epica','Tropa',6,8,'Baja','Tierra'),
(52,'El Tronco','Legendaria','Hechizo',6,2,'N/A','N/A'),
(53,'Chispitas','Legendaria','Tropa',6,6,'Baja','Tierra'),
(54,'Minero','Legendaria','Tropa',6,3,'Alta','Tierra'),
(55,'Barbaros de Elite','Comun','Tropa',7,6,'Muy Alta','Tierra'),
(56,'Gigante Noble','Comun','Tropa',7,6,'Baja','Tierra'),
(57,'Megaesbirrio','Especial','Tropa',7,3,'Media','Aire'),
(58,'Trio de Mosqueteras','Especial','Tropa',7,9,'Media','Tierra'),
(59,'Principe Oscuro','Epica','Tropa',7,4,'Media','Tierra'),
(60,'Guardias','Epica','Tropa',7,3,'Alta','Tierra'),
(61,'Mago electrico','Legendaria','Tropa',7,4,'Alta','Tierra'),
(62,'Princesa','Legendaria','Tropa',7,3,'Media','Tierra'),
(63,'Murcielagos','Comun','Tropa',8,2,'Muy Alta','Aire'),
(64,'Espiritu de hielo','Comun','Tropa',8,1,'Muy Alta','Tierra'),
(65,'Golem de hielo','Especial','Tropa',8,2,'Baja','Tierra'),
(66,'Clon','Epica','Hechizo',8,3,'N/A','N/A'),
(67,'Lanzarrocas','Epica','Tropa',8,5,'Baja','Tierra'),
(68,'Bruja Nocturna','Legendaria','Tropa',8,4,'Media','Tierra'),
(69,'Leñador','Legendaria','Tropa',8,4,'Muy Alta','Tierra'),
(70,'Pandilla de duendes','Comun','Tropa',9,3,'Muy Alta','Tierra'),
(71,'Duende lanzadardos','Especial','Tropa',9,3,'Muy Alta','Tierra'),
(72,'Verdugo','Epica','Tropa',9,5,'Media','Tierra'),
(73,'Bandida','Legendaria','Tropa',9,3,'Alta','Tierra'),
(74,'Curacion','Especial','Hechizo',10,3,'N/A','N/A');

/* Creado por josé gonzález */ ;
/* 	JOGOB LABS */ ;
